import ArgumentParser
import Foundation
import StorescreensCore

struct InitCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "init",
        abstract: "Generate a storescreens.yml config file."
    )

    @Option(name: .long, help: "Xcode project or workspace to detect scheme from.")
    var project: String?

    @Flag(name: .long, help: "Overwrite existing config file.")
    var force: Bool = false

    func run() async throws {
        let logger = Logger()
        let outputPath = "storescreens.yml"

        if FileManager.default.fileExists(atPath: outputPath) && !force {
            logger.log("storescreens.yml already exists. Use --force to overwrite.", level: .warning)
            return
        }

        logger.header("Generating storescreens.yml")

        let detector = ProjectDetector()

        // Detect project/workspace
        let (detectedProject, detectedWorkspace) = detector.detectProjectFile()
        let projectPath = project ?? detectedProject
        let workspacePath = detectedWorkspace

        guard projectPath != nil || workspacePath != nil else {
            logger.log("No .xcodeproj or .xcworkspace found in current directory.", level: .error)
            logger.log("Run this command from your Xcode project directory.", level: .info)
            return
        }

        // Detect scheme
        let detectedScheme = await detector.detectScheme(
            project: projectPath, workspace: workspacePath
        ) ?? "MyApp"
        logger.log("Detected scheme: \(detectedScheme)", level: .success)

        // Check platform - must target iOS or macOS
        let platforms = await detector.detectSupportedPlatforms(
            project: projectPath, workspace: workspacePath, scheme: detectedScheme
        )
        let hasIOS = platforms.isEmpty || platforms.contains(where: { $0.contains("iphone") })
        let hasMacOS = platforms.contains(where: { $0.contains("macos") || $0.contains("macosx") })
        if !hasIOS && !hasMacOS {
            logger.log("This project does not target iOS or macOS.", level: .error)
            logger.log("storescreens requires an iOS, macOS, or universal project.", level: .info)
            return
        }
        if hasMacOS && !hasIOS {
            logger.log("Detected macOS-only project", level: .success)
        }

        // Detect deployment target so we only pick compatible simulators
        let deploymentTarget: String?
        if hasIOS {
            deploymentTarget = await detector.detectDeploymentTarget(
                project: projectPath, workspace: workspacePath, scheme: detectedScheme
            )
            if let target = deploymentTarget {
                logger.log("Detected deployment target: iOS \(target)", level: .success)
            }
        } else {
            deploymentTarget = nil
        }

        // Pick default devices
        var deviceConfigs: [DeviceConfig] = []

        if hasIOS {
            // Pick iOS devices using screen dimensions from CoreSimulator profiles
            let manager = SimulatorManager()
            let devices = try await manager.listAvailableDevices(minimumRuntime: deploymentTarget)
            var sizeMap: [String: AppStoreScreenSize] = [:]
            for device in devices {
                sizeMap[device.udid] = try await manager.appStoreSize(for: device)
            }
            let defaultDevices = pickDefaultDevices(from: devices, sizeMap: sizeMap)

            // Warn about missing required App Store sizes
            detector.warnMissingRequiredSizes(sizeMap: sizeMap, logger: logger)

            deviceConfigs.append(contentsOf: defaultDevices.map { DeviceConfig(simulator: $0.name) })
        }

        if hasMacOS {
            // Add a default Mac App Store size (13" Retina)
            deviceConfigs.append(DeviceConfig(simulator: "Mac 2560x1600", platform: "macOS"))
            logger.log("Added Mac 2560x1600 (13\" Retina) for Mac App Store", level: .success)
        }

        logger.log("Selected \(deviceConfigs.count) default device(s)", level: .success)

        // Build config
        var config = CaptureConfig(
            scheme: detectedScheme,
            devices: deviceConfigs,
            outputDir: "./storescreens-output"
        )
        if let ws = workspacePath {
            config.workspace = ws
        } else if let proj = projectPath {
            config.project = proj
        }

        // Write YAML manually for readable output with comments
        var yaml = "# storescreens.yml - Generated by storescreens init\n"
        yaml += "# Docs: https://github.com/ciscoriordan/storescreens-cli\n\n"

        if let ws = config.workspace {
            yaml += "workspace: \"\(ws)\"\n"
        } else if let proj = config.project {
            yaml += "project: \"\(proj)\"\n"
        } else {
            yaml += "# project: MyApp.xcodeproj\n"
        }

        yaml += "scheme: \"\(config.scheme)\"\n\n"

        yaml += "devices:\n"
        for device in config.devices {
            yaml += "  - simulator: \"\(device.simulator)\"\n"
            if let platform = device.platform {
                yaml += "    platform: \(platform)\n"
            }
        }

        yaml += "\n# Optional: capture in multiple locales\n"
        yaml += "# locales:\n"
        yaml += "#   - en-US\n"
        yaml += "#   - ja\n"
        yaml += "#   - de-DE\n\n"

        yaml += "# Optional: custom flags for the HTML preview gallery.\n"
        yaml += "# Keys are Xcode locale codes; values are either a filename (without .svg)\n"
        yaml += "# from ciscoriordan/svg-flags/circle/languages/, or a full https:// URL.\n"
        yaml += "# Merged with built-in defaults; these win on collisions.\n"
        yaml += "# locale_flags:\n"
        yaml += "#   en-IN: in-en\n"
        yaml += "#   hi: in-hi\n\n"

        yaml += "# Appearances to capture (default: both light and dark)\n"
        yaml += "# appearances:\n"
        yaml += "#   - light\n"
        yaml += "#   - dark\n\n"

        yaml += "# Optional: filter screenshots by XCTAttachment name\n"
        yaml += "# screenshots:\n"
        yaml += "#   - \"01_HomeScreen\"\n"
        yaml += "#   - \"02_Settings\"\n\n"

        yaml += "output_dir: \"\(config.outputDir)\"\n\n"

        yaml += "# warmup_run: true\n\n"

        yaml += "# Run history: 1 = overwrite (default), 0 = keep all, N = keep last N\n"
        yaml += "# keep_runs: 1\n\n"

        yaml += "# Preflight: scan source for iPad-unsafe patterns before capture.\n"
        yaml += "# Default: true. Set to false to disable.\n"
        yaml += "# preflight: true\n\n"

        yaml += "# Optional: test target/class for xctest mode\n"
        yaml += "# test_target: MyAppUITests\n"
        yaml += "# test_class: ScreenshotTests\n"

        try yaml.write(toFile: outputPath, atomically: true, encoding: .utf8)

        logger.log("Wrote \(outputPath)", level: .success)
        logger.log("Edit the file, then run: storescreens capture", level: .info)
    }

    private func pickDefaultDevices(
        from devices: [SimulatorDevice],
        sizeMap: [String: AppStoreScreenSize]
    ) -> [SimulatorDevice] {
        let iPhones = devices
            .filter { sizeMap[$0.udid]?.isIPhone == true }
            .sorted { (sizeMap[$0.udid]?.width ?? 0) > (sizeMap[$1.udid]?.width ?? 0) }

        // Default: pick the largest iPhone (6.9") - App Store Connect generates
        // smaller sizes automatically. Users can add more devices in the config file.
        if let largest = iPhones.first {
            return [largest]
        }
        return []
    }
}
